// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Mahjong.proto

package com.geekerstar.mahjong.common.proto;

public interface StartGameMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StartGameMessage)
    com.google.protobuf.MessageOrBuilder {
}
