package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/HOLDING.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/workspace/8-2-build-macosx-x86_64/jdk8u181/11358/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Saturday, July 7, 2018 1:04:12 AM PDT
*/

public interface HOLDING
{

  /** Object adapter state that holds requests temporarily until the 
     * state is changed.
     */
  public static final short value = (short)(0);
}
